name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutar pruebas
        run: python -m unittest discover tests

      - name: Simular despliegue
        run: echo "Despliegue ejecutado correctamente"
